######################################################################
# Automatically generated by qmake (1.07a) Thu Feb 26 12:58:30 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += qargumentparser.h qswitchargument.h
SOURCES += main.cpp qargumentparser.cpp qswitchargument.cpp
CONFIG += qt warn_on create_prl link_prl static
OBJECTS_DIR=.obj
MOC_DIR=.moc
mac:CONFIG -= app_bundle

